cupcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),

    path('about/', views.about, name='about'),

    path('cups/', views.cups_index, name='index'),

    path('cups/<int:cup_id>/', views.cups_detail, name='detail'),

    path('cups/create/', views.CupCreate.as_view(), name='cups_create'),

    path('cups/<int:pk>/update/', views.CupUpdate.as_view(), name='cups_update'),

    path('cups/<int:pk>/delete/', views.CupDelete.as_view(), name='cups_delete'),

    path('cups/<int:cup_id>/add_use/', views.add_use, name='add_use'),

    path('cups/<int:cup_id>/assoc_content/<int:content_id>/', views.assoc_content, name='assoc_content'),

    path('contents/create/', views.ContentCreate.as_view(), name='contents_create'),

    path('contents/', views.ContentsIndex.as_view(), name='contents_index'),

    path('contents/<int:pk>/', views.ContentsDetail.as_view(), name='contents_detail'),

    path('contents/<int:pk>/update/', views.ContentUpdate.as_view(), name='contents_update'),

    path('contents/<int:pk>/delete/', views.ContentDelete.as_view(), name='contents_delete'),

    path('accounts/signup/', views.signup, name='signup'),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date
from django.contrib.auth.models import User

STATUS = (
    ('C', 'Clean'),
    ('D', 'Dirty')
)


class Content(models.Model):
    name = models.CharField(max_length=50)
    temp = models.CharField(max_length=20)

    def __str__(self):
        return f'{self.temp} {self.name}'

    def get_absolute_url(self):
        return reverse('contents_detail', kwargs={'pk': self.id})


class Cup(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    # age = models.IntegerField()
    contents = models.ManyToManyField(Content)

    def __str__(self):
        return f'the cups name is {self.name}'

    def get_absolute_url(self):
        return reverse('detail', kwargs = { 'cup_id': self.id })
    user = models.ForeignKey(User, on_delete=models.CASCADE) 


class Use(models.Model):
  date = models.DateField('use date')
  status = models.CharField(
    max_length=1,
    choices=STATUS,
    default=STATUS[0][0]
  )

  
  cup = models.ForeignKey(Cup, on_delete=models.CASCADE)

def __str__(self):
    return f"{self.get_status_display()} on {self.date}"

class Meta:
    ordering = ['-date']

main_app/forms.py
from django.forms import ModelForm
from .models import Use

class UseForm(ModelForm):
  class Meta:
    model = Use
    fields = ['date', 'status']

main_app/views.py
from django.views.generic import ListView, DetailView

from django.contrib.auth import login

from django.contrib.auth.forms import UserCreationForm

from django.contrib.auth.decorators import login_required

from django.contrib.auth.mixins import LoginRequiredMixin

from django.shortcuts import render

from django.http import HttpResponse

from django.views.generic.edit import CreateView, UpdateView, DeleteView

from .models import Cup, Content

from .forms import UseForm

from django.shortcuts import render, redirect



# cups = [
#   Cup('Lolo', 'foul little demon'),
#   Cup('Sachi', 'diluted tortoise shell'),
#   Cup('Raven', '3 legged cat')
# ]



#Home View
def home(request):
  return HttpResponse('<h1>Welcome to Cup Collector! </h1>')

#About View
def about(request):
  return render(request, 'about.html')

@login_required
def cups_index(request):
  cups = Cup.objects.filter(user=request.user)
  return render(request, 'cups/index.html', { 'cups': cups })

@login_required
def cups_detail(request, cup_id):
    cup = Cup.objects.get(id=cup_id)

    contents_cup_doesnt_have = Content.objects.exclude(id__in = cup.contents.all().values_list('id'))
    cup.contents.all().values_list('id')

    use_form = UseForm()
    return render(request, 'cups/detail.html', {'cup': cup, 'use_form': use_form, 'contents': contents_cup_doesnt_have})


def signup(request):
  error_message = ''
  if request.method == 'POST':
    form = UserCreationForm(request.POST)
    if form.is_valid():
      user = form.save()
      login(request, user)
      return redirect('index')
    else:
      error_message = 'Invalid sign up - try again'
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'registration/signup.html', context)


@login_required
def add_use(request, cup_id):
    form = UseForm(request.POST)
    if form.is_valid():
       new_use = form.save(commit=False)
       new_use.cup_id = cup_id
       new_use.save()
    return redirect('detail', cup_id=cup_id)


@login_required
def assoc_content(request, cup_id, content_id):
  Cup.objects.get(id=cup_id).contents.add(content_id)
  return redirect('detail', cup_id=cup_id)



class CupCreate(LoginRequiredMixin, CreateView):
  model = Cup
  fields = ('name', 'description')
  def form_valid(self, form):
    form.instance.user = self.request.user
    return super().form_valid(form)

class CupUpdate(LoginRequiredMixin, UpdateView):
    model = Cup
    fields = ['description']

class CupDelete(LoginRequiredMixin, DeleteView):
    model = Cup
    success_url = '/cups/'



class ContentsIndex(LoginRequiredMixin, ListView):
    model = Content

class ContentsDetail(LoginRequiredMixin, DetailView):
    model = Content

class ContentCreate(LoginRequiredMixin, CreateView):
    model = Content
    fields = '__all__'

class ContentUpdate(UpdateView):
    model = Content
    fields = '__all__'

class ContentDelete(LoginRequiredMixin, DeleteView):
    model = Content
    success_url = '/contents/'

main_app/templates/about.html
{% extends 'base.html' %} {% block content %}

<h1>About the Cup Collector</h1>
<hr />
<p>Use the Cup Collector to keep track and display your favorite cups and mugs!</p>

{% endblock %}

</html>

main_app/templates/base.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Cup Collector</title>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"
    />

<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  </head>
  <body>
    <header class="navbar-fixed teal lighten-2">
      <nav>
        <div class="nav-wrapper teal lighten-2">
          <ul>
            <li>
              <a href="/" class="left brand-logo  teal lighten-2">  CupCollector</a>
            </li>
          </ul>
          <ul class="right teal lighten-2">
            <li><a href="/about">About</a></li>

            {% if user.is_authenticated %}
            <li><a href="{% url 'contents_create' %}">Add a Content</a></li>
            <li><a href="{% url 'contents_index' %}">View All Contents</a></li>
            <li><a href="{% url 'cups_create' %}">Add a Cup</a></li>
            <li><a href="{% url 'index' %}">View All My Cups</a></li>
            <li><a href="{% url 'logout' %}">Log Out</a></li>
            {% else %}
            <li><a href="{% url 'signup' %}">Sign Up</a></li>
            <li><a href="{% url 'login' %}">Log In</a></li>
            {% endif %}
          </ul>
        </div>
      </nav>
    </header>
    <main class="container">{% block content %} {% endblock %}</main>
    <footer class="page-footer teal lighten-2">
      <div class="right teal lighten-2">
        All Rights Reserved, © 2023 Cup Collector  
      </div>
    </footer>
  </body>
</html>

main_app/templates/cups/detail.html
{% extends 'base.html' %} {% block content %}

<h1>Cup Details</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ cup.name }}</span>
        <p>Description: {{ cup.description }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'cups_update' cup.id %}">Edit</a>
        <a href="{% url 'cups_delete' cup.id %}">Delete</a>
      </div>
    </div>
  </div>
  <div class="col s6">
    <form action="{% url 'add_use' cup.id %}" method="post">
        {% csrf_token %} {{ use_form.as_p }}
        <input type="submit" class="btn #212121 grey darken-4" value="Add Use" />
      </form>
    <table class="striped">
      <thead>
        <tr>
          <th>Date</th>
          <th>Status</th>
        </tr>
      </thead>
      <tbody>
        {% for use in cup.use_set.all %}
        <tr>
          <td>{{use.date}}</td>
          <td>{{use.get_status_display}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>


<hr />
<div class="row">
  <div class="col s6">
    <h3>{{ cup.name }}'s Contents</h3>
    {% if cup.contents.count %} {% for content in cup.contents.all %}
    <div class="card">
      <div class="card-content">
        <span class="card-title">
          A <span style="temp: {{ content.temp }}">{{ content.temp }}</span> {{ content.name }}
        </span>
      </div>
    </div>
    {% endfor %} {% else %}
    <h5>No Contents :(</h5>
    {% endif %}
  </div>
  <div class="col s6">
    <h3>Available Contents</h3>
    {% if contents.count %}
      {% for content in contents.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              A <span style="temp: {{ content.temp }}"> {{ content.temp }}</span> {{ content.name }}
            </span>
          </div>
        </div>
          <div class="card-action">
            <form action="{% url 'assoc_content' cup.id content.id %}" method="post">
              {% csrf_token %}
              <button type="submit" class="btn">Add</button>
            </form>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>{{cup.name}} Already Has All Contents Available</h5>
    {% endif %}
  </div>



<script>
  var dateEl = document.getElementById('id_date');
  M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  });
  var selectEl = document.getElementById('id_status');
  M.FormSelect.init(selectEl);
</script>
{% endblock %}

main_app/templates/cups/index.html
{% extends 'base.html' %} {% block content %}

<h1>Cup List</h1>

{% for cup in cups %}
<div class="card">
    <a href="{% url 'detail' cup.id %}">
  <div class="card-content">
    <span class="card-title">{{ cup.name }}</span>
    <p>Description: {{ cup.description }}</p>
  </div>
 </a>
</div>
{% endfor %} {% endblock %}

main_app/templates/main_app/content_confirm_delete.html
{% extends 'base.html' %} {% block content %}
<h1>Delete Content</h1>

<h4>
  Are you sure you want to delete <span class="card-title">the<span class="{{content.temp.lower}}-text"> {{ content.temp.capitalize }}</span> {{ content.name }}</span>?
</h4>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes - Delete!" class="btn" />
  <a href="{% url 'contents_detail' object.id %}">Cancel</a>
</form>
{% endblock %} 

main_app/templates/main_app/content_detail.html
{% extends 'base.html' %} {% block content %}

<h1>Content Details</h1>

<div class="card">
    <a href="{% url 'contents_detail' content.id %}">
        <div class="card-content">
            <span class="card-title"> <span class="{{content.temp.lower}}-text">{{ content.temp.capitalize }}</span>
                {{ content.name }}</span>
        </div>
    </a>
    <div class="card-action">
        <a href="{% url 'contents_update' content.id %}">Edit</a>
        <a href="{% url 'contents_delete' content.id %}">Delete</a>
    </div>
</div>

{% endblock %}

main_app/templates/main_app/content_form.html
{% extends 'base.html' %} {% block content%}
<form action='' method='POST' autocomplete="off">

    {% csrf_token %}
    {% if object %}
    <h1>Edit <span class="teal-text">{{ object.name }}</span></h1>
    {% else %}
    <h1>Add Content</h1>
    {% endif%}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" class="btn blue" />
</form>

{% endblock%}

main_app/templates/main_app/content_list.html
{% extends 'base.html' %} {% block content %}

<h1>Content List</h1>

{% for content in object_list %}
<div class="card">
  <a href="{% url 'contents_detail' content.id %}" >
  <div class="card-content">
    <span class="card-title"> <span class="{{content.temp.lower}}-text">{{ content.temp.capitalize }}</span> {{ content.name }}</span>
  </div>
  </a>
</div>
{% endfor %} {% endblock %}

main_app/templates/main_app/cup_confirm_delete.html
{% extends 'base.html' %} {% block content %}
<h1>Delete Cup</h1>

<h4>
  Are you sure you want to delete
  <span class="teal-text">{{ object.name }}</span>?
</h4>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes - Delete!" class="btn" />
  <a href="{% url 'detail' cup.id %}">Cancel</a>
</form>
{% endblock %}

main_app/templates/main_app/cup_form.html
{% extends 'base.html' %} {% block content %}
{% if object %}
<h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
<h1>Add Cup</h1>
{% endif %}

<form action="" method="post">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <input type="submit" value="Submit!" class="btn" />
</form>
{% endblock %}